<?php


/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "api" middleware group. Enjoy building your API!
|
*/
use Illuminate\Support\Facades\Route;

Route::middleware('throttle:60,1')->namespace('Api')->prefix('v1')->group(function () {
    /********************************************共有权限********************************************************/
    Route::match(['get','post'],'report/verifyCode','v1\LoginController@setVerifyCode')->name('reportCode');
    Route::match(['get','post'],'login','v1\LoginController@index')->name('apiLogin');
    Route::match(['get','post'],'config','v1\LoginController@config')->name('getConfig');
    Route::match(['get','post'],'file/download','v1\LoginController@download')->name('downloadFile');
    Route::match(['get','post'],'sendEmail','v1\LoginController@email')->name('sendEmail');
    Route::match(['get','post'],'checkCode','v1\LoginController@code')->name('checkCode');
    Route::match(['get','post'],'checkLogin','v1\MenuController@check')->name('checkLogin');
    Route::match(['get','post'],'logout','v1\MenuController@logout')->name('apiLogout');
    Route::match(['get','post'],'menu','v1\MenuController@getMenu')->name('menu');
    Route::match(['get','post'],'total','v1\MenuController@getCountData')->name('total');
    Route::match(['get','post'],'getCityName','v1\MenuController@getCityName')->name('getCityName');
    Route::match(['get','post'],'confirmMail','v1\ResetPasswordController@sendMail')->name('confirmMail');
    Route::match(['get','post'],'resetPass','v1\ResetPasswordController@resetPass')->name('resetPass');
    /********************************************共有权限********************************************************/

    /********************************************私有权限********************************************************/
    //管理员
    Route::match(['get','post'],'user/index','v1\UsersController@index');
    Route::match(['get','post'],'user/update','v1\UsersController@update')->name('userUpdate');
    Route::match(['get','post'],'user/save','v1\UsersController@save');
    Route::match(['get','post'],'user/center','v1\UsersController@center')->name('userCenter');
    Route::match(['get','post'],'center/save','v1\UsersController@saveCenter')->name('saveCenter');
    Route::match(['get','post'],'user/bind','v1\UsersController@getBindInfo')->name('getBindInfo');
    Route::match(['get','post'],'user/delete','v1\UsersController@delete');
    //小程序
    Route::match(['get','post'],'wx/login','v1\WxUsersController@login')->name('wxLogin');
    Route::match(['get','post'],'wx/getOpenid','v1\WxUsersController@getOpenId')->name('getOpenId');
    Route::match(['get','post'],'wx/upload','v1\WxUsersController@upload');
    //权限
    Route::match(['get','post'],'auth/index','v1\AuthController@index');
    Route::match(['get','post'],'auth/save','v1\AuthController@save');
    Route::match(['get','post'],'auth/update','v1\AuthController@update');
    Route::match(['get','post'],'auth/delete','v1\AuthController@delete');
    //授权
    Route::match(['get','post'],'oauth/index','v1\OauthController@index');
    Route::match(['get','post'],'oauth/sendMail','v1\OauthController@email');
    Route::match(['get','post'],'oauth/update','v1\OauthController@update');
    Route::match(['get','post'],'oauth/delete','v1\OauthController@delete');
    Route::match(['get','post'],'oauth/verifyCode','v1\OauthController@code');
    Route::match(['get','post'],'oauth/bind','v1\OauthController@oauthBind');
    Route::match(['post','get'],'oauth/chat','v1\OauthController@getChatOAuthLists')->name('chat');

    //请求授权
    Route::match(['get','post'],'req-rule/index','v1\ReqRuleController@index');
    Route::match(['get','post'],'req-rule/save','v1\ReqRuleController@save')->name('reqRuleSave');
    Route::match(['get','post'],'req-rule/update','v1\ReqRuleController@update');
    Route::match(['get','post'],'req-rule/delete','v1\ReqRuleController@delete');
    Route::match(['get','post'],'req-rule/getAuth','v1\ReqRuleController@getAuth');
    //日志
    Route::match(['get','post'],'log/index','v1\LogController@index');
    Route::match(['get','post'],'log/save','v1\LogController@save')->name('logSave');
    Route::match(['get','post'],'log/delete','v1\LogController@delete')->name('logDelete');
    //配置
    Route::match(['get','post'],'config/index','v1\ConfigController@index');
    Route::match(['get','post'],'config/save','v1\ConfigController@save');
    Route::match(['get','post'],'config/update','v1\ConfigController@update');
    Route::match(['get','post'],'config/updateVal','v1\ConfigController@value');
    Route::match(['get','post'],'config/delete','v1\ConfigController@delete');
    //文件
    Route::match(['get','post'],'file/index','v1\FileController@index');
    Route::match(['get','post'],'file/read','v1\FileController@read');
    Route::match(['get','post'],'file/save','v1\FileController@save');
    Route::match(['get','post'],'file/update','v1\FileController@update');
    Route::match(['get','post'],'file/rename','v1\FileController@rename');
    Route::match(['get','post'],'file/chmod','v1\FileController@auth');
    Route::match(['get','post'],'file/zip','v1\FileController@compression');
    Route::match(['get','post'],'file/unzip','v1\FileController@Decompression');
    Route::match(['get','post'],'file/upload','v1\FileController@upload')->name('uploadFile');
    Route::match(['get','post'],'file/delete','v1\FileController@delete');
    Route::match(['get','post'],'image/preview','v1\FileController@preview');
    //角色
    Route::match(['get','post'],'role/index','v1\RoleController@index');
    Route::match(['get','post'],'role/update','v1\RoleController@update');
    Route::match(['get','post'],'role/save','v1\RoleController@save');
    Route::match(['get','post'],'role/delete','v1\RoleController@delete');
    //数据库
    Route::match(['get','post'],'database/index','v1\DatabaseController@index');
    Route::match(['get','post'],'database/backup','v1\DatabaseController@backup');
    Route::match(['get','post'],'database/repair','v1\DatabaseController@repair');
    Route::match(['get','post'],'database/optimize','v1\DatabaseController@optimize');
    Route::match(['get','post'],'database/comment','v1\DatabaseController@comment');
    //城市
    Route::match(['get','post'],'area/index','v1\AreaController@index');
    Route::match(['get','post'],'area/weather','v1\AreaController@weather');
    Route::match(['get','post'],'area/lists','v1\AreaController@lists')->name('areaLists');
    //站内信息推送
    Route::match(['get','post'],'push/index','v1\PushController@index');
    Route::match(['get','post'],'push/save','v1\PushController@save');
    Route::match(['get','post'],'push/update','v1\PushController@update');
    Route::match(['get','post'],'push/see','v1\PushController@read');
    Route::match(['get','post'],'push/delete','v1\PushController@delete');
    //API接口
    Route::match(['get','post'],'api/index','v1\ApiController@index');
    Route::match(['post','get'],'api/update','v1\ApiController@update');
    Route::match(['post','get'],'api/save','v1\ApiController@save');
    //API接口
    Route::match(['get','post'],'apidoc/index','v1\ApiDocController@index');
    Route::match(['post','get'],'apidoc/update','v1\ApiDocController@update');
    Route::match(['post','get'],'apidoc/save','v1\ApiDocController@save');
    //API接口分类
    Route::match(['post','get'],'category/index','v1\ApiController@category');
    Route::match(['post','get'],'category/delete','v1\ApiController@CategoryDelete');
    Route::match(['post','get'],'category/save','v1\ApiController@categorySave');
    Route::match(['post','get'],'category/update','v1\ApiController@CategoryUpdate');
    //表情
    Route::match(['post','get'],'emotion/index','v1\EmotionController@index')->name('emotion');
    //excel导入导出
    Route::match(['post','get'],'excel/import','v1\ExcelController@import');
    Route::match(['post','get'],'excel/export','v1\ExcelController@export')->name('export');
    //组件
    Route::match(['post','get'],'components/table','v1\TableComponentController@table');
    Route::match(['post','get'],'components/actions','v1\TableComponentController@action');
    //时间线
    Route::match(['post','get'],'timeline/index','v1\TimeLineController@index');
    Route::match(['post','get'],'timeline/save','v1\TimeLineController@save');
    Route::match(['post','get'],'timeline/update','v1\TimeLineController@update');
    /********************************************私有权限********************************************************/

    /******************************************第三方登陆**********************************************************/
    //QQ
    Route::get('oauth-login/qq','v1\OauthLoginController@QQ')->name('qqLogin');
    Route::get('callback/qq','v1\OauthCallbackController@QQ')->name('qqCallback');
    //Github
    Route::get('oauth-login/github','v1\OauthLoginController@gitHub')->name('gitHubLogin');
    Route::get('callback/github','v1\OauthCallbackController@gitHub')->name('gitHubCallback');
    //WeiBo
    Route::get('oauth-login/weibo','v1\OauthLoginController@weibo')->name('weiboLogin');
    Route::get('callback/weibo','v1\OauthCallbackController@weibo')->name('weiboCallback');
    //Gitee
    Route::get('oauth-login/gitee','v1\OauthLoginController@gitee')->name('giteeLogin');
    Route::get('callback/gitee','v1\OauthCallbackController@gitee')->name('giteeCallback');
    //Baidu
    Route::get('oauth-login/baidu','v1\OauthLoginController@baidu')->name('baiduLogin');
    Route::get('callback/baidu','v1\OauthCallbackController@baidu')->name('baiduCallback');
    //osChina
    Route::get('oauth-login/os_china','v1\OauthLoginController@osChina')->name('osChinaLogin');
    Route::get('callback/os_china','v1\OauthCallbackController@osChina')->name('osChinaCallback');
    /******************************************第三方登陆**********************************************************/

});
