<?php
define('Host','127.0.0.1');
define('Port','3306');
define('UserName','root');
define('Password','');
define('DbName','longer');
define('RedisKey','uidConnectionMap');
define('BgImg','http://www.laravel.com/bg.png');
define('KFImg','http://www.laravel.com/kf.jpg');
